name: deploy-production

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      PREFIX_DEPLOY_RENDER_WEBHOOK :
        required: true


jobs:
  test-curl-action:
    name: "Webhook Auto Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Call webhook trigger auto deploy"
        uses: indiesdev/curl@v1.1
        id: api
        with:
          url:  ${{ secrets.PREFIX_DEPLOY_RENDER_WEBHOOK }}&${{ inputs.image_name }}
          method: "GET"
          accept: 201, 200
          log-response: true
      - name: "Use secrets"
        run: echo ${{ secrets.PREFIX_DEPLOY_RENDER_WEBHOOK }}&
      - name: "Use response"
        run: echo ${{ steps.api.outputs.response }}